from __future__ import annotations

from xml.sax.saxutils import escape, quoteattr

from .core import lineage_graph


def lineage_graphml(document: dict) -> str:
    graph = lineage_graph(document)
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">',
        '  <key id="node_kind" for="node" attr.name="kind" attr.type="string"/>',
        '  <key id="node_field" for="node" attr.name="field" attr.type="string"/>',
        '  <key id="node_value" for="node" attr.name="value" attr.type="string"/>',
        '  <key id="edge_mapping_id" for="edge" attr.name="mapping_id" attr.type="string"/>',
        '  <key id="edge_transform" for="edge" attr.name="transform" attr.type="string"/>',
        '  <key id="edge_reference" for="edge" attr.name="reference" attr.type="string"/>',
        '  <graph id="mapping-lineage" edgedefault="directed">',
    ]
    for node in graph["nodes"]:
        lines.append(f"    <node id={quoteattr(str(node['id']))}>")
        lines.append(f"      <data key=\"node_kind\">{escape(str(node.get('kind', '')))}</data>")
        if node.get("field") is not None:
            lines.append(f"      <data key=\"node_field\">{escape(str(node['field']))}</data>")
        if node.get("value") is not None:
            lines.append(f"      <data key=\"node_value\">{escape(str(node['value']))}</data>")
        lines.append("    </node>")
    for index, edge in enumerate(graph["edges"]):
        edge_id = str(edge.get("id") or f"edge-{index}")
        lines.append(
            f"    <edge id={quoteattr(edge_id)} source={quoteattr(str(edge['from']))} target={quoteattr(str(edge['to']))}>"
        )
        lines.append(f"      <data key=\"edge_mapping_id\">{escape(edge_id)}</data>")
        lines.append(f"      <data key=\"edge_transform\">{escape(str(edge.get('transform', 'copy')))}</data>")
        if edge.get("reference") is not None:
            lines.append(f"      <data key=\"edge_reference\">{escape(str(edge['reference']))}</data>")
        lines.append("    </edge>")
    lines.extend(["  </graph>", "</graphml>"])
    return "\n".join(lines) + "\n"


def _cypher_string(value: object) -> str:
    text = str(value)
    text = text.replace("\\", "\\\\").replace("'", "\\'").replace("\r", "\\r").replace("\n", "\\n")
    return f"'{text}'"


def lineage_cypher(document: dict) -> str:
    graph = lineage_graph(document)
    lines = ["// Generated by Mapping as Code. Deterministic field-level lineage."]
    for node in graph["nodes"]:
        props = [f"id: {_cypher_string(node['id'])}", f"kind: {_cypher_string(node.get('kind', ''))}"]
        if node.get("field") is not None:
            props.append(f"field: {_cypher_string(node['field'])}")
        if node.get("value") is not None:
            props.append(f"value: {_cypher_string(node['value'])}")
        lines.append(f"MERGE (n:MappingLineageNode {{id: {_cypher_string(node['id'])}}}) SET n += {{{', '.join(props)}}};")
    for edge in graph["edges"]:
        mapping_id = str(edge.get("id") or "mapping")
        transform = str(edge.get("transform") or "copy")
        reference = edge.get("reference")
        properties = [f"mapping_id: {_cypher_string(mapping_id)}", f"transform: {_cypher_string(transform)}"]
        if reference is not None:
            properties.append(f"reference: {_cypher_string(reference)}")
        lines.append(
            "MATCH (s:MappingLineageNode {id: %s}), (t:MappingLineageNode {id: %s}) "
            "MERGE (s)-[r:MAPS_TO {mapping_id: %s}]->(t) SET r += {%s};"
            % (
                _cypher_string(edge["from"]),
                _cypher_string(edge["to"]),
                _cypher_string(mapping_id),
                ", ".join(properties),
            )
        )
    return "\n".join(lines) + "\n"
